{% set name = "dbscan" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/dbscan-{{ version }}.tar.gz
  sha256: 8ea6c8b72b8ff98d12422a3b9d7c56c3feac5390ab18b4be5e37042124ada1ce

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
    - setuptools-scm
    - wheel
    - numpy
    - pip
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - dbscan
  source_files:
    - test/*.py
  commands:
    - pip check
    - pytest test/
  requires:
    - pip
    - pytest
    - scikit-learn

about:
  home: https://github.com/wangyiqiu/dbscan-python
  summary: Theoretically efficient and practical parallel DBSCAN
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - wangyiqiu
    - anivegesana
